import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../../styles/globals.css";
import { getServerSession } from "next-auth";
import { Sidebar } from "@/common/components/Sidebar";
import { authOptions } from "../../../auth";
import AuthProvider from "../_providers/AuthProvider";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const session = await getServerSession(authOptions);

	// if (!session) {
	// 	redirect("/signin");
	// }

	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<AuthProvider session={session}>
					<main className="relative grid gap-4  grid-cols-[280px_1fr]">
						<Sidebar />
						<section className="grid grid-rows-[20px_1fr_20px] items-center justify-items-center min-h-screen p-2 pb-20 gap-16 sm:p-8">
							{children}
						</section>
					</main>
				</AuthProvider>
			</body>
		</html>
	);
}
